### ISSUE TITLE
No such file or directory: 'README.md' with pip install

### ISSUE THREAD

**Issue by jinfenglin** [sebastianGehrmann/dblp-pub#2]
When I try to pip install I got the following errors. I guess if it is because the PyPI has an old version. 
```
pip install dblp
Collecting dblp
  Using cached dblp-0.1.0.tar.gz (3.3 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\ljfnw\appdata\local\programs\python\python37\python.exe'                                              -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ljfnw\\AppD                                             ata\\Local\\Temp\\pip-install-esrvpkok\\dblp\\setup.py'"'"'; __file__='"'"'C:\\U                                             sers\\ljfnw\\AppData\\Local\\Temp\\pip-install-esrvpkok\\dblp\\setup.py'"'"';f=g                                             etattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n                                             '"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' eg                                             g_info --egg-base 'C:\Users\ljfnw\AppData\Local\Temp\pip-install-esrvpkok\dblp\p                                             ip-egg-info'
         cwd: C:\Users\ljfnw\AppData\Local\Temp\pip-install-esrvpkok\dblp\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ljfnw\AppData\Local\Temp\pip-install-esrvpkok\dblp\setup.py                                             ", line 12, in <module>
        long_description=open('README.md').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check th                                             e logs for full command output.
```

**Comment by prkhrv** [comment]
Yes, Getting the same Issue.
